### ISSUE TITLE
Proposition d'amélioration de l'ordre des # dans le profil

### ISSUE THREAD

**Issue by CaMi773** [gigagg/GigaTribe#28]
Ce n'est pas un bug mais, j'ai l'impression que les # sont classé par id de création dans le profil, est il possible que nous puissions classé a notre convenance les # dans notre profil ?
En les classant par exemple par ordre d'ajout dans le profil.

**Comment by gigagg** [comment]
Ça devrait fonctionner dans la version 3.05.033

**Comment by CaMi773** [comment]
oui ca fonctionne, par contre on est obligé de rentré et sauvegardé un part un les #
