### ISSUE TITLE
problème de déconnexion

### ISSUE THREAD

**Issue by chris26200** [gigagg/GigaTribe#38]
Depuis que j'ai téléchargé la dernière version, GIGA se déconnecte toutes les 5 minutes

**Comment by mitch59460** [comment]
Bonjour, je viens de faire la dernière mise à jour du site et depuis ça se déconnecte tout seul au bout de 5 à 10 minutes.

**Comment by gigagg** [comment]
Ce bug est normalement corrigé dans la version 3.05.030

**Comment by Nike57** [comment]
Plus ce bug avec la 3.025.030
