### ISSUE TITLE
Version Linux

### ISSUE THREAD

**Issue by RLilie** [gigagg/GigaTribe#40]
Bonjour, j'écris cette demande d'amélioration pour avoir une version Linux (Je suis sous Linux Mint). 

En vous remerciant d'avance de ce que vous faites.

**Comment by gigagg** [comment]
Je travaille sur la version linux. La difficulté c'est le packaging...

**Comment by tguyard** [comment]
Il y a une version linux de dispo (encore en beta, comme toutes les version 3.05)
