### ISSUE TITLE
Canaux de mise a jour

### ISSUE THREAD

**Issue by CaMi773** [gigagg/GigaTribe#43]
Bonjour, 

Avec la mise a jour automatique de la v3.05 il n'est plus possible de faire un retour sur une version plus stable de gigatribe. Est il possible de faire au moins deux canaux de mise a jour l'un dernière version stable et l'autre les versions d’essais.

**Comment by gigagg** [comment]
En effet, je vais voir pour mettre ça en place

**Comment by CaMi773** [comment]
Bonjour, impossible d'installer la version bêta 3.07.001 sans désinstaller la 3.06.005. Pouvez vous regarder si c'est possible de faire un canal de mise a jour bêta.

**Comment by CaMi773** [comment]
Les mise à jour bêta fonctionne a part, donc c'est opérationnelle. merci
