### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Maxaren2** [gigagg/GigaTribe#52]
Crash systematique de l'application quand je vais sur éditer mon profil 
Je viens de mettre à jour mon application en 3.05.028
W10 pro 64bits. Update de windows de novembre faite il y a deux jours .

**Comment by gigagg** [comment]
Ce bug est normalement corrigé dans la version 3.05.030

**Comment by Nike57** [comment]
Après plusieurs essais , ce bug n'est plus présent avec la 3.05.030
