### ISSUE TITLE
Récapitulatifs des propositions des membres 

### ISSUE THREAD

**Issue by Nike57** [gigagg/GigaTribe#57]
Ce n'est pas un bug ,mais je me permet de faire une récap de toutes les améliorations ou options que les membres ont réclamés pour l'application Gigagtribe. 

- pack de smileys un peu plus étoffé .
- deux canaux de mise a jour l'un dernière version stable et l'autre les versions d’essais.
- Une version Linux 
- le choix pour un mode sombre ou clair
- Classement personnalisé les # dans notre profil "par ordre d'ajout dans le profil par exemple"

**Comment by Nike57** [comment]
Le monde sombre a était intégré .

**Comment by gigagg** [comment]
Fait : 

- Une version Linux
- le choix pour un mode sombre ou clair
- Classement personnalisé les # dans notre profil "par ordre d'ajout dans le profil par exemple"

Pour les autres demande cf : #49 et #43.
