### ISSUE TITLE
Les # sur liens externe

### ISSUE THREAD

**Issue by CaMi773** [gigagg/GigaTribe#68]
Bonjour, 

Comme les invitations de membres par liens externe (gigatribe://nom d'utilisateur), est il possible d'ajouter les # par liens externe (gigatribe://#video).

**Comment by gigagg** [comment]
Bonjour, 

Dans la version 3.05.033, les liens de type "gigatribe://hashtag/video" seront pris en charge. 
(Pour des raisons techniques il n'est pas possible de faire des liens avec le format "gigatribe://#video".)

**Comment by CaMi773** [comment]
Bonjour, oui effectivement. :)
