### ISSUE TITLE
infos sur les mises a jour

### ISSUE THREAD

**Issue by Nike57** [gigagg/GigaTribe#74]
Serait il possible ,lorsqu'une nouvelle mise a jour sort . D'indiquer les améliorations qui ont étaient faîtes sur cette dernière ?

**Comment by Maxaren2** [comment]
On appelle ça un changeLOG et je trouve votre idée plus qu'intéressante

**Comment by Nike57** [comment]
Merci pour l'info

**Comment by CaMi773** [comment]
Salut je pense que c'est résolu.
https://github.com/gigagg/GigaTribe/blob/master/changelog.md
